// front/src/components/LanguageSwitcher.vue
<script setup lang="ts">
import { ref } from "vue";
import { useI18n } from "vue-i18n";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { Button } from "@/components/ui/button";
import { Globe } from "lucide-vue-next";
import { LANG_STORAGE_KEY } from "@/i18n";

interface LanguageSwitcherProps {
  isCollapsed: boolean;
}

const props = defineProps<LanguageSwitcherProps>();

const { locale } = useI18n();
const languages = [
  { code: "en", name: "English" },
  { code: "zh", name: "中文" },
];
const isOpen = ref(false);

const handleLanguageSelect = (langCode: string) => {
  locale.value = langCode;
  localStorage.setItem(LANG_STORAGE_KEY, langCode);
  isOpen.value = false;
};

const currentLanguageName = () => {
  return languages.find((lang) => lang.code === locale.value)?.name;
};
</script>

<template>
  <div class="mt-auto p-2 border-t border-gray-100">
    <Popover v-model:open="isOpen">
      <PopoverTrigger as-child>
        <Button
          variant="ghost"
          class="w-full flex items-center py-1.5 px-2.5 rounded-md text-gray-500 hover:bg-gray-100 hover:text-gray-700 transition-colors h-auto border-0 text-sm"
          :class="{
            'justify-center': props.isCollapsed,
            'justify-start': !props.isCollapsed,
          }"
          aria-label="Change language"
        >
          <Globe class="h-4 w-4 flex-shrink-0" />
          <span
            v-if="!props.isCollapsed"
            class="ml-2 font-medium whitespace-nowrap overflow-hidden"
          >
            {{ currentLanguageName() }}
          </span>
        </Button>
      </PopoverTrigger>
      <PopoverContent
        class="p-1 w-36 mb-2 border-gray-200 bg-white text-gray-700 shadow-lg"
        :class="{ 'ml-2': props.isCollapsed }"
      >
        <div class="grid gap-0.5">
          <Button
            v-for="lang in languages"
            :key="lang.code"
            variant="ghost"
            class="w-full justify-start text-sm hover:bg-gray-100 hover:text-gray-900"
            :class="{
              'font-semibold text-blue-600 bg-blue-50': locale === lang.code,
            }"
            @click="handleLanguageSelect(lang.code)"
          >
            {{ lang.name }}
          </Button>
        </div>
      </PopoverContent>
    </Popover>
  </div>
</template>

// front/src/components/LanguageSwitcher.tsx
import { Component, For, createSignal, Show } from 'solid-js';
import { Popover, PopoverTrigger, PopoverContent } from './ui/Popover';
import { Button } from './ui/Button';
import { setLocale, currentLocale } from '../i18n';

const GlobeIcon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9V3m0 18a9 9 0 009-9m-9 9a9 9 0 00-9-9" />
    </svg>
);

interface LanguageSwitcherProps {
  isCollapsed: boolean;
}

const LanguageSwitcher: Component<LanguageSwitcherProps> = (props) => {
  const languages = [
    { code: 'en', name: 'English' },
    { code: 'zh', name: '中文' }
  ];
  const [isOpen, setIsOpen] = createSignal(false);

  const handleLanguageSelect = (langCode: string) => {
    setLocale(langCode);
    setIsOpen(false);
  };

  const currentLanguage = () => languages.find(lang => lang.code === currentLocale());

  return (
    <div class="mt-auto px-4 py-2 border-t border-slate-700">
      <Popover placement="top" open={isOpen()} onOpenChange={setIsOpen}>
        <PopoverTrigger
          as={(p) => (
            <Button
              {...p}
              variant="ghost"
              class="w-full flex items-center py-2.5 px-4 rounded-md text-sm text-slate-300 hover:bg-slate-700 hover:text-white group"
              classList={{
                'justify-center': props.isCollapsed
              }}
              aria-label="Change language"
            >
              <span class="w-6 text-center flex-shrink-0">
                <GlobeIcon />
              </span>
              <Show when={!props.isCollapsed}>
                <span class="ml-3 whitespace-nowrap overflow-hidden">
                  {currentLanguage()?.name}
                </span>
              </Show>
            </Button>
          )}
        />
        <PopoverContent class="p-1 w-40 mb-2 bg-slate-900 border-slate-700 text-white">
          <div class="grid gap-1">
            <For each={languages}>
              {(lang) => (
                <Button
                  variant="ghost"
                  class="w-full justify-start text-white hover:bg-slate-700"
                  classList={{ 'font-bold bg-indigo-600 hover:bg-indigo-500': currentLocale() === lang.code }}
                  onClick={() => handleLanguageSelect(lang.code)}
                >
                  {lang.name}
                </Button>
              )}
            </For>
          </div>
        </PopoverContent>
      </Popover>
    </div>
  );
};

export default LanguageSwitcher;
