// front/src/pages/ApiKey.vue
<template>
  <CrudPageLayout
    :title="$t('apiKeyPage.title')"
    :description="$t('apiKeyPage.description') || $t('apiKeyPage.title')"
    :loading="loading"
    :error="error"
    :empty="!apiKeyStore.apiKeys.length"
    header-class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4"
  >
    <template #actions>
      <Button variant="outline" @click="handleStartEditing()">
        <Plus class="h-4 w-4 mr-1.5" />
        {{ $t("apiKeyPage.addApiKey") }}
      </Button>
    </template>

    <template #loading>
      <div class="flex flex-col items-center justify-center py-20">
        <Loader2 class="h-5 w-5 animate-spin text-gray-400 mb-2" />
        <span class="text-sm font-medium text-gray-500">{{
          $t("apiKeyPage.loading")
        }}</span>
      </div>
    </template>

    <template #error="{ error }">
      <div class="flex flex-col items-center justify-center py-20">
        <div
          class="text-red-600 bg-red-50 border border-red-200 rounded-lg p-4 max-w-lg text-sm"
        >
          {{ $t("apiKeyPage.errorPrefix") }} {{ error }}
        </div>
      </div>
    </template>

    <template #empty>
      <div class="flex flex-col items-center justify-center py-20">
        <KeyRound class="h-10 w-10 stroke-1 text-gray-400 mb-4" />
        <span class="text-sm font-medium text-gray-500">{{
          $t("apiKeyPage.noData")
        }}</span>
      </div>
    </template>

    <div class="border border-gray-200 rounded-lg overflow-hidden">
      <Table>
        <TableHeader class="bg-gray-50/80 hover:bg-gray-50/80">
          <TableRow>
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("apiKeyPage.table.name") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("apiKeyPage.table.apiKeyPartial") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("apiKeyPage.table.description") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("apiKeyPage.table.enabled") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("apiKeyPage.table.accessControlPolicy") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("apiKeyPage.table.createdAt") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("apiKeyPage.table.updatedAt") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider text-right"
              >{{ $t("apiKeyPage.table.actions") }}</TableHead
            >
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow v-for="key in apiKeyStore.apiKeys" :key="key.id">
            <TableCell class="font-medium text-gray-900">{{
              key.name
            }}</TableCell>
            <TableCell>
              <div class="flex items-center space-x-2">
                <span class="font-mono text-xs text-gray-600">{{
                  key.api_key
                    ? `${key.api_key.substring(0, 3)}...${key.api_key.substring(key.api_key.length - 4)}`
                    : "N/A"
                }}</span>
                <Button
                  variant="ghost"
                  size="sm"
                  class="h-6 w-6 p-0 text-gray-400 hover:text-gray-900"
                  @click="copyApiKeyToClipboard(key.api_key, key.id)"
                  :title="$t('apiKeyPage.copy')"
                >
                  <Check
                    v-if="copiedKeyId === key.id"
                    class="h-3 w-3 text-green-600"
                  />
                  <Copy v-else class="h-3 w-3" />
                </Button>
              </div>
            </TableCell>
            <TableCell
              class="max-w-xs truncate text-gray-500"
              :title="key.description || ''"
              >{{ key.description || "/" }}</TableCell
            >
            <TableCell>
              <Checkbox
                :checked="key.is_enabled"
                @update:checked="(val: boolean) => handleToggleEnable(key, val)"
              />
            </TableCell>
            <TableCell>
              <Badge
                variant="secondary"
                v-if="(key as any).access_control_policy_name"
                class="font-mono text-xs"
              >
                {{ (key as any).access_control_policy_name }}
              </Badge>
              <span v-else class="text-gray-400">-</span>
            </TableCell>
            <TableCell class="text-gray-500 text-sm">{{
              key.created_at_formatted || key.created_at
            }}</TableCell>
            <TableCell class="text-gray-500 text-sm">{{
              key.updated_at_formatted || key.updated_at
            }}</TableCell>
            <TableCell class="text-right">
              <Button
                variant="ghost"
                size="sm"
                class="text-gray-500 hover:text-gray-900 px-2"
                @click="handleStartEditing(key)"
              >
                <Pencil class="h-3.5 w-3.5 mr-1" />
                {{ $t("common.edit") }}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                class="text-gray-400 hover:text-red-600 px-2"
                @click="handleDeleteApiKey(key)"
              >
                <Trash class="h-3.5 w-3.5 mr-1" />
                {{ $t("common.delete") }}
              </Button>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </div>

    <template #modals>
      <!-- Edit Modal -->
      <ApiKeyEditModal
        v-model:isOpen="showEditModal"
        :initial-data="selectedApiKey"
        @save-success="handleSaveSuccess"
      />
    </template>
  </CrudPageLayout>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useI18n } from "vue-i18n";
import { Api } from "@/services/request";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import {
  Plus,
  Loader2,
  KeyRound,
  Copy,
  Check,
  Pencil,
  Trash,
} from "lucide-vue-next";
import CrudPageLayout from "@/components/CrudPageLayout.vue";
import ApiKeyEditModal from "@/components/ApiKeyEditModal.vue";
import { useApiKeyStore } from "@/store/apiKeyStore";
import { useAccessControlStore } from "@/store/accessControlStore";
import { toastController } from "@/lib/toastController";
import { confirm } from "@/lib/confirmController";

const { t: $t } = useI18n();

const apiKeyStore = useApiKeyStore();
const accessControlStore = useAccessControlStore();

const showEditModal = ref(false);
const selectedApiKey = ref<any | null>(null);
const copiedKeyId = ref<number | null>(null);
const loading = ref(true);
const error = ref<string | null>(null);

const fetchData = async () => {
  loading.value = true;
  error.value = null;
  try {
    await Promise.all([
      apiKeyStore.fetchApiKeys(),
      accessControlStore.fetchPolicies(),
    ]);
  } catch (err: any) {
    error.value = err.message || $t("common.unknownError");
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  fetchData();
});

const handleStartEditing = (apiKey?: any) => {
  selectedApiKey.value = apiKey || null;
  showEditModal.value = true;
};

const handleToggleEnable = async (apiKey: any, newVal: boolean) => {
  const updatedApiKey = { ...apiKey, is_enabled: newVal };
  try {
    const payload = {
      name: updatedApiKey.name,
      api_key: updatedApiKey.api_key,
      description: updatedApiKey.description,
      is_enabled: updatedApiKey.is_enabled,
      access_control_policy_id: updatedApiKey.access_control_policy_id,
    };
    await Api.updateApiKey(updatedApiKey.id, payload);
    await apiKeyStore.fetchApiKeys(); // Refetch to update data
  } catch (err: any) {
    console.error("Failed to toggle API key status:", err);
    toastController.error(
      $t("apiKeyPage.toggleStatusFailed", {
        error: err.message || $t("common.unknownError"),
      }),
    );
    await apiKeyStore.fetchApiKeys(); // Refetch to revert
  }
};

const handleSaveSuccess = async () => {
  await apiKeyStore.fetchApiKeys();
  showEditModal.value = false;
  selectedApiKey.value = null;
};

const handleDeleteApiKey = async (apiKey: any) => {
  if (
    await confirm($t("apiKeyPage.confirmDelete", { name: apiKey.name }))
  ) {
    try {
      await Api.deleteApiKey(apiKey.id);
      await apiKeyStore.fetchApiKeys();
    } catch (err: any) {
      console.error("Failed to delete API key:", err);
      toastController.error(
        $t("apiKeyPage.deleteFailed", { error: err.message || $t("common.unknownError") }),
      );
    }
  }
};

const copyApiKeyToClipboard = async (apiKeyString: string, keyId: number) => {
  if (!apiKeyString) return;
  try {
    await navigator.clipboard.writeText(apiKeyString);
    copiedKeyId.value = keyId;
    setTimeout(() => {
      copiedKeyId.value = null;
    }, 2000);
  } catch (err) {
    console.error("Failed to copy API key: ", err);
    toastController.error($t("apiKeyPage.copyFailed"));
  }
};
</script>

// front/src/pages/ApiKey.tsx
import { createSignal, For, Show, createResource } from 'solid-js';
import { Button } from '../components/ui/Button';
import {
    TableRoot,
    TableHeader,
    TableBody,
    TableRow,
    TableColumnHeader,
    TableCell,
} from '../components/ui/Table';
import { useI18n } from '../i18n'; // Import the i18n hook
import { request } from '../services/api';
import { apiKeys as globalApiKeys, refetchApiKeys as globalRefetchApiKeys } from '../store/apiKeyStore';
import type { ApiKeyItem } from '../store/types';
import ApiKeyEditModal from '../components/ApiKeyEditModal'; // Import the new modal component
import { fetchPoliciesAPI, type AccessControlPolicyFromAPI } from './AccessControlPage';
// EditingApiKeyData interface is now in ApiKeyEditModal.tsx

const formatTimestamp = (ms: number | undefined | null): string => {
    if (!ms) return '';
    const date = new Date(ms);
    const YYYY = date.getFullYear();
    const MM = String(date.getMonth() + 1).padStart(2, '0');
    const DD = String(date.getDate()).padStart(2, '0');
    const hh = String(date.getHours()).padStart(2, '0');
    const mm = String(date.getMinutes()).padStart(2, '0');
    const ss = String(date.getSeconds()).padStart(2, '0');
    return `${YYYY}-${MM}-${DD} ${hh}:${mm}:${ss}`;
};

// fetchApiKeys is now in apiKeyStore.ts

export default function ApiKeyPage() {
    const [t] = useI18n(); // Initialize the t function
    const [policies] = createResource<AccessControlPolicyFromAPI[]>(fetchPoliciesAPI, { initialValue: [] });
    const [showEditModal, setShowEditModal] = createSignal(false);
    // This will hold the ApiKeyItem to edit, or null for a new one
    const [selectedApiKey, setSelectedApiKey] = createSignal<ApiKeyItem | null>(null);
    const [copiedKeyId, setCopiedKeyId] = createSignal<number | null>(null);

    const handleStartEditing = (apiKey?: ApiKeyItem) => {
        setSelectedApiKey(apiKey || null); // Set to null for new, or the item for editing
        setShowEditModal(true);
    };

    const handleToggleEnable = async (apiKey: ApiKeyItem) => {
        const updatedApiKey = { ...apiKey, is_enabled: !apiKey.is_enabled };
        try {
            // Prepare payload, similar to what ApiKeyEditModal would send for an update
            // The backend expects the full key data for an update.
            const payload = {
                name: updatedApiKey.name,
                api_key: updatedApiKey.api_key, // Send existing key, backend might ignore or re-validate
                description: updatedApiKey.description,
                is_enabled: updatedApiKey.is_enabled,
                access_control_policy_id: (updatedApiKey as any).access_control_policy_id,
            };
            await request(`/ai/manager/api/system_api_key/${updatedApiKey.id}`, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload),
            });
            globalRefetchApiKeys();
        } catch (error) {
            console.error("Failed to toggle API key status:", error);
            alert(t('apiKeyPage.toggleStatusFailed', { error: error instanceof Error ? error.message : t('unknownError') }));
            // Optionally, refetch to revert optimistic UI changes if any were made,
            // or revert the checkbox state manually if it was optimistically updated.
            // For now, a refetch will correct the UI.
            globalRefetchApiKeys();
        }
    };

    const handleCloseModal = () => {
        setShowEditModal(false);
        setSelectedApiKey(null); // Clear selected data when modal closes
    };

    const handleSaveSuccess = () => {
        globalRefetchApiKeys();
        // The modal will call its own onClose, but we ensure state is clean here too
        handleCloseModal();
    };

    const handleDeleteApiKey = async (apiKey: ApiKeyItem) => {
        if (confirm(t('apiKeyPage.confirmDelete', { name: apiKey.name }))) {
            try {
                await request(`/ai/manager/api/system_api_key/${apiKey.id}`, { method: 'DELETE' });
                globalRefetchApiKeys();
            } catch (error) {
                console.error("Failed to delete API key:", error);
                alert(t('deleteFailed', { error: (error as Error).message || t('unknownError') }));
            }
        }
    };

    const copyApiKeyToClipboard = (apiKeyString: string, keyId: number) => {
        if (!apiKeyString) return;
        const textArea = document.createElement("textarea");
        textArea.value = apiKeyString;
        
        // Prevent scrolling to bottom of page in MS Edge.
        textArea.style.top = "0";
        textArea.style.left = "0";
        textArea.style.position = "fixed";

        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();

        try {
            const successful = document.execCommand('copy');
            if (successful) {
                setCopiedKeyId(keyId);
                setTimeout(() => setCopiedKeyId(null), 2000); // Reset after 2 seconds
            } else {
                console.error('Failed to copy API key using execCommand.');
                alert(t('apiKeyPage.copyFailed'));
            }
        } catch (err) {
            console.error('Failed to copy API key: ', err);
            alert(t('apiKeyPage.copyFailed'));
        }

        document.body.removeChild(textArea);
    };


    return (
        <div class="p-4 space-y-6">
            <h1 class="text-2xl font-semibold mb-4 text-gray-800">{t('apiKeyPage.title')}</h1>

            <div class="mb-4">
                <Button variant="primary" onClick={() => handleStartEditing()}>{t('apiKeyPage.addApiKey')}</Button>
            </div>

            {/* Data Table */}
            <Show when={globalApiKeys.loading}>
                <div class="text-center py-4 text-gray-500">{t('apiKeyPage.loading')}</div>
            </Show>
            <Show when={!globalApiKeys.loading && globalApiKeys.error}>
                <div class="text-center py-4 text-red-600 bg-red-100 border border-red-400 rounded p-4">
                    {t('apiKeyPage.errorPrefix')} {globalApiKeys.error instanceof Error ? globalApiKeys.error.message : t('unknownError')}
                </div>
            </Show>
            <Show when={!globalApiKeys.loading && !globalApiKeys.error && globalApiKeys()?.length === 0}>
                 <div class="text-center py-4 text-gray-500">{t('apiKeyPage.noData')}</div>
            </Show>

            <Show when={!globalApiKeys.loading && !globalApiKeys.error && globalApiKeys() && globalApiKeys()!.length > 0}>
                <div class="overflow-x-auto shadow-md rounded-lg border border-gray-200">
                    <TableRoot>
                        <TableHeader>
                            <TableRow>
                                <TableColumnHeader>{t('apiKeyPage.table.name')}</TableColumnHeader>
                                <TableColumnHeader>{t('apiKeyPage.table.apiKeyPartial')}</TableColumnHeader>
                                <TableColumnHeader>{t('apiKeyPage.table.description')}</TableColumnHeader>
                                <TableColumnHeader>{t('apiKeyPage.table.enabled')}</TableColumnHeader>
                                <TableColumnHeader>{t('apiKeyPage.table.accessControlPolicy')}</TableColumnHeader>
                                <TableColumnHeader>{t('apiKeyPage.table.createdAt')}</TableColumnHeader>
                                <TableColumnHeader>{t('apiKeyPage.table.updatedAt')}</TableColumnHeader>
                                <TableColumnHeader>{t('apiKeyPage.table.actions')}</TableColumnHeader>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            <For each={globalApiKeys()}>
                                {(key) => (
                                    <TableRow>
                                        <TableCell>{key.name}</TableCell>
                                        <TableCell class="font-mono">
                                            {key.api_key ? `${key.api_key.substring(0, 3)}...${key.api_key.substring(key.api_key.length - 4)}` : 'N/A'}
                                            <Button variant="ghost" size="xs" class="ml-2" onClick={() => copyApiKeyToClipboard(key.api_key, key.id)} title={t('apiKeyPage.copy')}>
                                                {copiedKeyId() === key.id ? t('apiKeyPage.copied') : t('apiKeyPage.copy')}
                                            </Button>
                                        </TableCell>
                                        <TableCell class="max-w-xs truncate" title={key.description}>{key.description || '/'}</TableCell>
                                        <TableCell>
                                            <input
                                                type="checkbox"
                                                class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
                                                checked={key.is_enabled}
                                                onChange={() => handleToggleEnable(key)}
                                            />
                                        </TableCell>
                                        <TableCell>{(key as any).access_control_policy_name || t('common.notAvailable')}</TableCell>
                                        <TableCell>{key.created_at_formatted}</TableCell>
                                        <TableCell>{key.updated_at_formatted}</TableCell>
                                        <TableCell class="space-x-2">
                                            <Button variant="primary" size="sm" onClick={() => handleStartEditing(key)}>{t('edit')}</Button>
                                            <Button variant="destructive" size="sm" onClick={() => handleDeleteApiKey(key)}>{t('delete')}</Button>
                                        </TableCell>
                                    </TableRow>
                                )}
                            </For>
                        </TableBody>
                    </TableRoot>
                </div>
            </Show>

            {/* Use the new ApiKeyEditModal component */}
            <Show when={policies()}>
                <ApiKeyEditModal
                    isOpen={showEditModal}
                    onClose={handleCloseModal}
                    initialData={selectedApiKey}
                    onSaveSuccess={handleSaveSuccess}
                    policies={policies()!}
                />
            </Show>
            
        </div>
    );
}
