// front/src/pages/ModelEdit.tsx
import { For, Show, onMount, createSignal, createResource } from 'solid-js';
import { createStore, produce } from 'solid-js/store';
import { useI18n } from '../i18n';
import { Button } from '../components/ui/Button';
import { TextField } from '../components/ui/Input';
import { Select } from '../components/ui/Select';
import {
    TableRoot,
    TableHeader,
    TableBody,
    TableRow,
    TableColumnHeader,
    TableCell,
} from '../components/ui/Table';
import { useNavigate, useParams } from '@solidjs/router';
import { request } from '../services/api';
import { toastController } from '../components/GlobalMessage';
import type { CustomFieldType } from '../store/types';
import { refetchProviders as globalRefetchProviders } from '../store/providerStore';

interface BillingPlan {
    id: number;
    name: string;
    currency: string;
}

interface PriceRule {
    id: number;
    plan_id: number;
    description: string | null;
    is_enabled: boolean;
    effective_from: number;
    effective_until: number | null;
    usage_type: string;
    media_type: string | null;
    price_in_micro_units: number;
}

// Local interface for custom fields, must include id for linking/unlinking
interface CustomFieldItem {
    id: number;
    field_name: string;
    field_value: string;
    description: string | null;
    field_type: CustomFieldType;
}

// Interface for the data being edited
interface EditingModelData {
    id: number;
    provider_id: number;
    billing_plan_id: number | null;
    model_name: string;
    real_model_name: string | null;
    is_enabled: boolean;
    custom_fields: CustomFieldItem[];
}

interface ModelItem {
    id: number;
    provider_id: number;
    billing_plan_id: number | null;
    model_name: string;
    real_model_name: string | null;
    is_enabled: boolean;
}

interface ModelDetailFromApi {
    model: ModelItem;
    custom_fields: CustomFieldItem[];
}

const fetchBillingPlans = async (): Promise<BillingPlan[]> => {
    try {
        const response = await request('/ai/manager/api/price/plan/list');
        return response || [];
    } catch (error) {
        console.error("Failed to fetch billing plans", error);
        toastController.error("Failed to fetch billing plans");
        return [];
    }
};

const fetchPriceRules = async (planId: number | null): Promise<PriceRule[]> => {
    if (!planId) return [];
    try {
        const response = await request(`/ai/manager/api/price/rule/list_by_plan?plan_id=${planId}`);
        return response || [];
    } catch (error) {
        console.error(`Failed to fetch price rules for plan ${planId}`, error);
        toastController.error(`Failed to fetch price rules for plan ${planId}`);
        return [];
    }
};

const fetchModelDetail = async (modelId: number): Promise<ModelDetailFromApi | null> => {
    try {
        const response = await request(`/ai/manager/api/model/${modelId}/detail`);
        return response || null;
    } catch (error) {
        console.error(`Failed to fetch model detail for ID ${modelId}`, error);
        return null;
    }
};

const fetchAllCustomFields = async (t: (key: string) => string): Promise<CustomFieldItem[]> => {
    try {
        const response = await request('/ai/manager/api/custom_field_definition/list');
        if (response && response.list) {
            return response.list.map((f: any) => ({
                id: f.id,
                field_name: f.field_name,
                field_value: (f.string_value ?? f.integer_value?.toString() ?? f.number_value?.toString() ?? f.boolean_value?.toString()) || '',
                description: f.description,
                field_type: (f.field_type?.toLowerCase() as CustomFieldType) || 'unset'
            }));
        }
        return [];
    } catch (error) {
        console.error('Failed to fetch all custom fields', error);
        toastController.error(t('modelEditPage.alert.fetchCustomFieldsFailed'));
        return [];
    }
};

const formatTimestamp = (ms: number | undefined | null): string => {
    if (!ms) return '';
    const date = new Date(ms);
    return date.toLocaleString();
};

export default function ModelEdit() {
    const navigate = useNavigate();
    const params = useParams();
    const modelId = params.id ? parseInt(params.id) : null;
    const [t] = useI18n();

    const [editingData, setEditingData] = createStore<EditingModelData | null>(null);
    const [allCustomFields, setAllCustomFields] = createSignal<CustomFieldItem[]>([]);
    const [selectedCustomFieldId, setSelectedCustomFieldId] = createSignal<number | null>(null);
    const [isLoading, setIsLoading] = createSignal<boolean>(true);
    const [error, setError] = createSignal<string | null>(null);

    const [billingPlans] = createResource(fetchBillingPlans);
    const [priceRules] = createResource(() => editingData?.billing_plan_id, fetchPriceRules);

    const selectedPlan = () => billingPlans()?.find(p => p.id === editingData?.billing_plan_id);

    const reloadData = async () => {
        if (!modelId) {
            setError(t('modelEditPage.alert.missingId'));
            setIsLoading(false);
            return;
        }

        setIsLoading(true);
        setError(null);

        const fields = await fetchAllCustomFields(t);
        setAllCustomFields(fields);

        const detail = await fetchModelDetail(modelId);
        if (detail) {
            setEditingData({
                id: detail.model.id,
                provider_id: detail.model.provider_id,
                billing_plan_id: detail.model.billing_plan_id ?? null,
                model_name: detail.model.model_name,
                real_model_name: detail.model.real_model_name ?? null,
                is_enabled: detail.model.is_enabled,
                custom_fields: (detail.custom_fields || []).map(f => ({
                    id: f.id,
                    field_name: f.field_name,
                    field_value: (f.string_value ?? f.integer_value?.toString() ?? f.number_value?.toString() ?? f.boolean_value?.toString()) || '',
                    description: f.description,
                    field_type: (f.field_type?.toLowerCase() as CustomFieldType) || 'unset'
                })),
            });
        } else {
            setError(t('modelEditPage.alert.loadDataFailed', { modelId: modelId }));
        }
        setIsLoading(false);
    };

    onMount(reloadData);

    const handleNavigateBack = () => {
        navigate('/provider'); // Navigate back to provider list
    };

    const handleSaveModel = async () => {
        const currentData = editingData;
        if (!currentData) return;

        if (!currentData.model_name.trim()) {
            toastController.warn(t('modelEditPage.alert.nameRequired'));
            return;
        }

        const payload = {
            model_name: currentData.model_name,
            real_model_name: currentData.real_model_name || null,
            is_enabled: currentData.is_enabled,
            billing_plan_id: currentData.billing_plan_id,
        };

        try {
            await request(`/ai/manager/api/model/${currentData.id}`, {
                method: 'PUT',
                body: JSON.stringify(payload)
            });
            toastController.success(t('modelEditPage.alert.updateSuccess'));
            globalRefetchProviders(); // To update provider list which shows models
            await reloadData();
        } catch (error) {
            console.error("Failed to save model:", error);
            toastController.error(t('modelEditPage.alert.saveFailed', { error: (error as Error).message || t('unknownError') }));
        }
    };

    const updateEditingDataField = (field: keyof EditingModelData, value: any) => {
        if (editingData) {
            setEditingData(field, value);
        }
    };

    const availableCustomFields = () => {
        if (!editingData) return [];
        const linkedIds = new Set(editingData.custom_fields.map(f => f.id));
        return allCustomFields().filter(f => f.id && !linkedIds.has(f.id));
    };

    const handleLinkCustomField = async () => {
        const field = selectedCustomFieldId();
        const modelId = editingData?.id;

        if (!field) {
            toastController.warn(t('modelEditPage.alert.selectFieldToLink'));
            return;
        }
        if (!modelId) {
            toastController.warn(t('modelEditPage.alert.modelNotLoaded'));
            return;
        }

        const fieldId = (field as any).id ?? field;

        try {
            await request('/ai/manager/api/custom_field_definition/link', {
                method: 'POST',
                body: JSON.stringify({
                    custom_field_definition_id: fieldId,
                    model_id: modelId,
                    is_enabled: true,
                }),
            });

            const fieldToAdd = allCustomFields().find(f => f.id === fieldId);
            if (fieldToAdd) {
                setEditingData('custom_fields', produce(fields => {
                    fields.push(fieldToAdd);
                }));
            }
            setSelectedCustomFieldId(null);
            toastController.success(t('modelEditPage.alert.linkSuccess'));
        } catch (error) {
            console.error("Failed to link custom field:", error);
            toastController.error(t('modelEditPage.alert.linkFailed', { error: (error as Error).message || t('unknownError') }));
        }
    };


    const handleUnlinkCustomField = async (fieldId: number, index: number) => {
        const modelId = editingData?.id;
        if (!modelId) {
            toastController.warn(t('modelEditPage.alert.modelIdNotFound'));
            return;
        }

        try {
            await request('/ai/manager/api/custom_field_definition/unlink', {
                method: 'POST',
                body: JSON.stringify({
                    custom_field_definition_id: fieldId,
                    model_id: modelId,
                }),
            });

            setEditingData('custom_fields', produce(fields => {
                fields.splice(index, 1);
            }));
            toastController.success(t('modelEditPage.alert.unlinkSuccess'));
        } catch (error) {
            console.error("Failed to unlink custom field:", error);
            toastController.error(t('modelEditPage.alert.unlinkFailed', { error: (error as Error).message || t('unknownError') }));
        }
    };

    return (
        <div class="p-4 space-y-6 bg-white rounded-lg shadow-xl max-w-3xl mx-auto my-8">
            <h1 class="text-2xl font-semibold mb-4 text-gray-800">{t('modelEditPage.title')}</h1>
            <Show when={isLoading()}>
                <div class="text-center py-4 text-gray-500">{t('modelEditPage.loading')}</div>
            </Show>
            <Show when={error()}>
                <div class="text-center py-4 text-red-600 bg-red-100 border border-red-400 rounded p-4">
                    {error()}
                </div>
            </Show>
            <Show when={!isLoading() && !error() && editingData}>
                <div class="space-y-4">
                    <TextField
                        label={<>{t('modelEditPage.labelModelName')} <span class="text-red-500">*</span></>}
                        value={editingData!.model_name}
                        onChange={(v) => updateEditingDataField('model_name', v)}
                    />
                    <TextField
                        label={t('modelEditPage.labelRealModelName')}
                        value={editingData!.real_model_name ?? ''}
                        onChange={(v) => updateEditingDataField('real_model_name', v)}
                    />
                    <div class="flex items-center space-x-2">
                        <input
                            type="checkbox"
                            id="is_enabled_model_checkbox"
                            class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
                            checked={editingData!.is_enabled}
                            onChange={(e) => updateEditingDataField('is_enabled', e.currentTarget.checked)}
                        />
                        <label for="is_enabled_model_checkbox" class="text-sm font-medium leading-none">{t('modelEditPage.labelEnabled')}</label>
                    </div>

                    {/* Price Management Section */}
                    <div class="section">
                        <h3 class="section-title">{t('modelEditPage.priceSection.title')}</h3>
                        <Select
                            label={t('modelEditPage.priceSection.labelBillingPlan')}
                            value={
                                [
                                    { id: null, name: t('modelEditPage.priceSection.noPlan') },
                                    ...(billingPlans() || [])
                                ].find(p => p.id === editingData!.billing_plan_id)
                            }
                            onChange={(v) => updateEditingDataField('billing_plan_id', v?.id ?? null)}
                            options={[
                                { id: null, name: t('modelEditPage.priceSection.noPlan') },
                                ...(billingPlans() || [])
                            ]}
                            optionValue="id"
                            optionTextValue="name"
                            placeholder={t('modelEditPage.priceSection.placeholderBillingPlan')}
                        />

                        <Show when={editingData!.billing_plan_id}>
                            <div class="mt-4">
                                <Show when={priceRules.loading}>
                                    <p>{t('modelEditPage.priceSection.loadingRules')}</p>
                                </Show>
                                <Show when={!priceRules.loading && priceRules() && priceRules()!.length > 0}>
                                    <h4 class="text-md font-semibold mb-2">{t('modelEditPage.priceSection.rulesTitle')}</h4>
                                    <TableRoot>
                                        <TableHeader>
                                            <TableRow>
                                                <TableColumnHeader>{t('pricePage.rules.table.description')}</TableColumnHeader>
                                                <TableColumnHeader>{t('pricePage.rules.table.enabled')}</TableColumnHeader>
                                                <TableColumnHeader>{t('pricePage.rules.table.usageType')}</TableColumnHeader>
                                                <TableColumnHeader>{t('pricePage.rules.table.mediaType')}</TableColumnHeader>
                                                <TableColumnHeader>{t('pricePage.rules.table.price')}</TableColumnHeader>
                                                <TableColumnHeader>{t('pricePage.rules.table.effectiveFrom')}</TableColumnHeader>
                                            </TableRow>
                                        </TableHeader>
                                        <TableBody>
                                            <For each={priceRules()}>
                                                {(rule) => (
                                                    <TableRow>
                                                        <TableCell>{rule.description}</TableCell>
                                                        <TableCell>{rule.is_enabled ? t('common.yes') : t('common.no')}</TableCell>
                                                        <TableCell>{rule.usage_type}</TableCell>
                                                        <TableCell>{rule.media_type || '-'}</TableCell>
                                                        <TableCell class="text-right">{rule.price_in_micro_units / 1000} {selectedPlan()?.currency}</TableCell>
                                                        <TableCell>{formatTimestamp(rule.effective_from)}</TableCell>
                                                    </TableRow>
                                                )}
                                            </For>
                                        </TableBody>
                                    </TableRoot>
                                </Show>
                            </div>
                        </Show>
                    </div>

                    {/* Custom Fields Section */}
                    <div class="section">
                        <h3 class="section-title">{t('modelEditPage.sectionCustomFields')}</h3>
                        <div class="section-header grid grid-cols-[1fr_1fr_1fr_1fr_auto] gap-2 items-center">
                            <span class="font-semibold">{t('modelEditPage.tableHeaderFieldName')}</span>
                            <span class="font-semibold">{t('modelEditPage.tableHeaderFieldValue')}</span>
                            <span class="font-semibold">{t('modelEditPage.tableHeaderDescription')}</span>
                            <span class="font-semibold">{t('modelEditPage.tableHeaderFieldType')}</span>
                            <span></span>
                        </div>
                        <For each={editingData!.custom_fields}>
                            {(field, index) => (
                                <div class="section-row grid grid-cols-[1fr_1fr_1fr_1fr_auto] gap-2 items-center mb-2">
                                    <TextField value={field.field_name} disabled />
                                    <TextField value={field.field_value} disabled />
                                    <TextField value={field.description ?? ''} disabled />
                                    <TextField value={field.field_type} disabled />
                                    <Button variant="destructive" size="sm" onClick={() => handleUnlinkCustomField(field.id, index())}>{t('common.delete')}</Button>
                                </div>
                            )}
                        </For>
                        <div class="mt-4 flex items-center gap-2">
                            <Select
                                value={availableCustomFields().find(f => f.id === selectedCustomFieldId())}
                                onChange={(v) => setSelectedCustomFieldId(v ? v.id : null)}
                                options={availableCustomFields()}
                                optionValue="id"
                                optionTextValue="field_name"
                                placeholder={t('modelEditPage.placeholderSelectCustomField')}
                            />
                            <Button variant="primary" size="sm" onClick={handleLinkCustomField} disabled={!selectedCustomFieldId()}>
                                {t('modelEditPage.buttonAddCustomField')}
                            </Button>
                        </div>
                    </div>

                    <div class="mt-6 flex justify-end space-x-2 pt-4 border-t">
                        <Button variant="secondary" onClick={handleNavigateBack}>{t('common.cancel')}</Button>
                        <Button variant="primary" onClick={handleSaveModel}>{t('common.save')}</Button>
                    </div>
                </div>
            </Show>
        </div>
    );
}

// front/src/pages/ModelEdit.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { Api } from "@/services/request";
import { normalizeError } from "@/lib/error";
import { toastController } from "@/lib/toastController";
import { useProviderStore } from "@/store/providerStore";
import type {
  CustomFieldType,
  CustomFieldItem,
  BillingPlan,
  PriceRule,
  CustomFieldDefinition,
  ModelDetailResponse,
} from "@/store/types";

import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import MobileCrudCard from "@/components/MobileCrudCard.vue";
import { formatTimestamp } from "@/lib/utils";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Loader2, Trash2 } from "lucide-vue-next";

interface EditingModelData {
  id: number;
  provider_id: number;
  billing_plan_id: number | null;
  model_name: string;
  real_model_name: string;
  is_enabled: boolean;
  custom_fields: CustomFieldItem[];
}

const { t } = useI18n();
const route = useRoute();
const router = useRouter();
const providerStore = useProviderStore();

const modelId = parseInt(route.params.id as string);
const isLoading = ref(true);
const modelDetail = ref<ModelDetailResponse | null>(null);
const allCustomFields = ref<CustomFieldItem[]>([]);
const billingPlans = ref<BillingPlan[]>([]);
const priceRules = ref<PriceRule[]>([]);
const isLoadingPriceRules = ref(false);

const editingData = ref<EditingModelData | null>(null);
const selectedCustomFieldId = ref<string | null>(null);

const toEditableCustomField = (
  field: Pick<
    CustomFieldDefinition,
    | "id"
    | "name"
    | "field_name"
    | "string_value"
    | "integer_value"
    | "number_value"
    | "boolean_value"
    | "description"
    | "field_type"
  >,
): CustomFieldItem => ({
  id: field.id,
  name: field.name,
  field_name: field.field_name,
  field_value:
    (field.string_value ??
      field.integer_value?.toString() ??
      field.number_value?.toString() ??
      field.boolean_value?.toString()) ||
    "",
  description: field.description,
  field_type: (field.field_type?.toLowerCase() as CustomFieldType) || "unset",
});

const fetchData = async () => {
  if (isNaN(modelId)) {
    toastController.error(
      t("modelEditPage.alert.loadDataFailed", { modelId: route.params.id }),
    );
    isLoading.value = false;
    return;
  }

  try {
    isLoading.value = true;
    const [detail, customFieldsRes, plans] = await Promise.all([
      Api.getModelDetail(modelId),
      Api.getCustomFieldList(),
      Api.getBillingPlanList(),
    ]);

    modelDetail.value = detail;
    billingPlans.value = plans;

    if (customFieldsRes && customFieldsRes.list) {
      allCustomFields.value = customFieldsRes.list.map(toEditableCustomField);
    }

    if (detail) {
      editingData.value = {
        id: detail.model.id,
        provider_id: detail.model.provider_id,
        billing_plan_id: detail.model.billing_plan_id ?? null,
        model_name: detail.model.model_name,
        real_model_name: detail.model.real_model_name ?? "",
        is_enabled: detail.model.is_enabled,
        custom_fields: (detail.custom_fields || []).map(toEditableCustomField),
      };
    }
  } catch (error: unknown) {
    const normalizedError = normalizeError(error, t("common.unknownError"));
    toastController.error(
      t("modelEditPage.alert.loadDataFailed", { modelId: modelId }),
      normalizedError.message,
    );
  } finally {
    isLoading.value = false;
  }
};

const fetchPriceRules = async (planId: number | null) => {
  if (!planId) {
    priceRules.value = [];
    return;
  }
  try {
    isLoadingPriceRules.value = true;
    priceRules.value = await Api.getPriceRuleListByPlan(planId);
  } catch (error: unknown) {
    const normalizedError = normalizeError(error, t("common.unknownError"));
    toastController.error(
      t("modelEditPage.priceSection.loadingRules"),
      normalizedError.message,
    );
    priceRules.value = [];
  } finally {
    isLoadingPriceRules.value = false;
  }
};

watch(
  () => editingData.value?.billing_plan_id,
  (newPlanId) => {
    if (newPlanId !== undefined) {
      fetchPriceRules(newPlanId);
    }
  },
  { immediate: true },
);

const selectedPlan = computed(() =>
  billingPlans.value.find((p) => p.id === editingData.value?.billing_plan_id),
);

const availableCustomFields = computed(() => {
  if (!editingData.value || !editingData.value.custom_fields) return [];
  const linkedIds = new Set(editingData.value.custom_fields.map((f) => f.id));
  return allCustomFields.value
    .filter((f) => f.id && !linkedIds.has(f.id))
    .map((f) => ({ ...f, displayName: f.name || f.field_name }));
});

const handleSaveModel = async () => {
  if (!editingData.value) return;

  if (!editingData.value.model_name.trim()) {
    toastController.warn(t("modelEditPage.alert.nameRequired"));
    return;
  }

  const payload = {
    model_name: editingData.value.model_name,
    real_model_name: editingData.value.real_model_name || null,
    is_enabled: editingData.value.is_enabled,
    billing_plan_id: editingData.value.billing_plan_id,
  };

  try {
    await Api.updateModel(editingData.value.id, payload);
    toastController.success(t("modelEditPage.alert.updateSuccess"));
    void providerStore.fetchProviders().catch((error) => {
      console.error("Failed to refresh providers after saving model:", error);
    });
    fetchData();
  } catch (error: unknown) {
    const normalizedError = normalizeError(error, t("common.unknownError"));
    toastController.error(
      t("modelEditPage.alert.saveFailed", {
        error: normalizedError.message,
      }),
    );
  }
};

const handleLinkCustomField = async () => {
  const fieldId = selectedCustomFieldId.value;
  const modelIdVal = editingData.value?.id;

  if (!fieldId) {
    toastController.warn(t("modelEditPage.alert.selectFieldToLink"));
    return;
  }
  if (!modelIdVal) {
    toastController.warn(t("modelEditPage.alert.modelNotLoaded"));
    return;
  }

  try {
    await Api.linkCustomField({
      custom_field_definition_id: parseInt(fieldId),
      model_id: modelIdVal,
      is_enabled: true,
    });

    selectedCustomFieldId.value = null;
    toastController.success(t("modelEditPage.alert.linkSuccess"));
    fetchData();
  } catch (error: unknown) {
    const normalizedError = normalizeError(error, t("common.unknownError"));
    toastController.error(
      t("modelEditPage.alert.linkFailed", {
        error: normalizedError.message,
      }),
    );
  }
};

const handleUnlinkCustomField = async (fieldId: number) => {
  const modelIdVal = editingData.value?.id;
  if (!modelIdVal) {
    toastController.warn(t("modelEditPage.alert.modelIdNotFound"));
    return;
  }

  try {
    await Api.unlinkCustomField({
      custom_field_definition_id: fieldId,
      model_id: modelIdVal,
    });

    toastController.success(t("modelEditPage.alert.unlinkSuccess"));
    fetchData();
  } catch (error: unknown) {
    const normalizedError = normalizeError(error, t("common.unknownError"));
    toastController.error(
      t("modelEditPage.alert.unlinkFailed", {
        error: normalizedError.message,
      }),
    );
  }
};

const handleNavigateBack = () => {
  router.push("/provider");
};

onMounted(() => {
  fetchData();
});
</script>

<template>
  <div class="app-page">
    <div class="app-page-shell app-page-shell--narrow">
      <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div class="min-w-0">
          <h1 class="text-lg font-semibold text-gray-900 tracking-tight sm:text-xl">
            {{ t("modelEditPage.title") }}
          </h1>
        </div>
        <div class="flex w-full flex-col gap-2 sm:w-auto">
          <Button variant="outline" @click="handleNavigateBack">
            {{ t("common.cancel") }}
          </Button>
        </div>
      </div>

      <div v-if="isLoading" class="flex items-center justify-center py-16">
        <Loader2 class="h-5 w-5 animate-spin text-gray-400 mr-2" />
        <span class="text-sm text-gray-500">{{
          t("modelEditPage.loading")
        }}</span>
      </div>

      <div
        v-else-if="!modelDetail"
        class="flex flex-col items-center justify-center py-20"
      >
        <div
          class="bg-destructive/10 text-destructive border border-destructive/20 rounded-lg p-6 text-center"
        >
          <p class="text-sm font-medium">
            {{ t("modelEditPage.alert.loadDataFailed", { modelId: modelId }) }}
          </p>
          <Button class="mt-4" @click="fetchData">{{ t("common.retry") }}</Button>
        </div>
      </div>

      <div v-else-if="editingData" class="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle>{{ t("common.basicInfo") }}</CardTitle>
        </CardHeader>
        <CardContent class="space-y-4">
          <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <div class="grid gap-1.5">
              <Label for="model_name" class="text-gray-700">
                {{ t("modelEditPage.labelModelName") }}
                <span class="text-red-500 ml-0.5">*</span>
              </Label>
              <Input id="model_name" v-model="editingData.model_name" />
            </div>

            <div class="grid gap-1.5">
              <Label for="real_model_name" class="text-gray-700">{{
                t("modelEditPage.labelRealModelName")
              }}</Label>
              <Input id="real_model_name" v-model="editingData.real_model_name" />
            </div>
          </div>

          <div
            class="flex items-center justify-between p-3.5 border border-gray-200 rounded-lg"
          >
            <Label for="is_enabled" class="cursor-pointer text-gray-700">
              {{ t("modelEditPage.labelEnabled") }}
            </Label>
            <Checkbox
              id="is_enabled"
              v-model:checked="editingData.is_enabled"
            />
          </div>
        </CardContent>
      </Card>

      <!-- Price Management Section -->
      <Card>
        <CardHeader>
          <CardTitle>{{ t("modelEditPage.priceSection.title") }}</CardTitle>
        </CardHeader>
        <CardContent class="space-y-6">
          <div class="grid gap-1.5">
            <Label class="text-gray-700">{{
              t("modelEditPage.priceSection.labelBillingPlan")
            }}</Label>
            <Select
              :model-value="editingData.billing_plan_id?.toString() || 'none'"
              @update:model-value="
                (val: any) =>
                  (editingData!.billing_plan_id =
                    val === 'none' ? null : parseInt(val as string))
              "
            >
              <SelectTrigger class="w-full">
                <SelectValue
                  :placeholder="
                    t('modelEditPage.priceSection.placeholderBillingPlan')
                  "
                />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="none">{{
                  t("modelEditPage.priceSection.noPlan")
                }}</SelectItem>
                <SelectItem
                  v-for="plan in billingPlans"
                  :key="plan.id"
                  :value="plan.id.toString()"
                >
                  {{ plan.name }}
                </SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div v-if="editingData.billing_plan_id" class="space-y-4">
            <div
              v-if="isLoadingPriceRules"
              class="flex items-center justify-center py-8"
            >
              <Loader2 class="h-5 w-5 animate-spin mr-2 text-gray-500" />
              <p class="text-sm text-gray-500">
                {{ t("modelEditPage.priceSection.loadingRules") }}
              </p>
            </div>
            <div v-else-if="priceRules.length > 0" class="space-y-3">
              <h4 class="text-sm font-semibold text-gray-700">
                {{ t("modelEditPage.priceSection.rulesTitle") }}
              </h4>
              <div class="space-y-3 md:hidden">
                <MobileCrudCard
                  v-for="rule in priceRules"
                  :key="rule.id"
                  :title="rule.description || '-'"
                  :description="formatTimestamp(rule.effective_from)"
                >
                  <div class="grid grid-cols-1 gap-3 text-sm min-[360px]:grid-cols-2">
                    <div class="space-y-1">
                      <p class="text-[11px] font-medium uppercase tracking-wide text-gray-500">
                        {{ t("pricePage.rules.table.enabled") }}
                      </p>
                      <div>
                        <Badge variant="secondary" class="font-mono text-xs">
                          {{ rule.is_enabled ? t("common.yes") : t("common.no") }}
                        </Badge>
                      </div>
                    </div>
                    <div class="space-y-1">
                      <p class="text-[11px] font-medium uppercase tracking-wide text-gray-500">
                        {{ t("pricePage.rules.table.usageType") }}
                      </p>
                      <p class="text-sm text-gray-900">{{ rule.usage_type }}</p>
                    </div>
                    <div class="space-y-1">
                      <p class="text-[11px] font-medium uppercase tracking-wide text-gray-500">
                        {{ t("pricePage.rules.table.mediaType") }}
                      </p>
                      <p class="text-sm text-gray-900">{{ rule.media_type || "-" }}</p>
                    </div>
                    <div class="space-y-1">
                      <p class="text-[11px] font-medium uppercase tracking-wide text-gray-500">
                        {{ t("pricePage.rules.table.price") }}
                      </p>
                      <p class="break-all font-mono text-sm text-gray-700">
                        {{ rule.price_in_micro_units / 1000 }} {{ selectedPlan?.currency }}
                      </p>
                    </div>
                  </div>
                </MobileCrudCard>
              </div>

              <div class="hidden overflow-hidden rounded-lg border border-gray-200 md:block">
                <Table>
                  <TableHeader>
                    <TableRow class="bg-gray-50/80 hover:bg-gray-50/80">
                      <TableHead
                        class="text-xs font-medium text-gray-500 uppercase tracking-wider"
                        >{{ t("pricePage.rules.table.description") }}</TableHead
                      >
                      <TableHead
                        class="w-[80px] text-center text-xs font-medium text-gray-500 uppercase tracking-wider"
                        >{{ t("pricePage.rules.table.enabled") }}</TableHead
                      >
                      <TableHead
                        class="text-xs font-medium text-gray-500 uppercase tracking-wider"
                        >{{ t("pricePage.rules.table.usageType") }}</TableHead
                      >
                      <TableHead
                        class="text-xs font-medium text-gray-500 uppercase tracking-wider"
                        >{{ t("pricePage.rules.table.mediaType") }}</TableHead
                      >
                      <TableHead
                        class="text-right text-xs font-medium text-gray-500 uppercase tracking-wider"
                        >{{ t("pricePage.rules.table.price") }}</TableHead
                      >
                      <TableHead
                        class="text-xs font-medium text-gray-500 uppercase tracking-wider"
                        >{{
                          t("pricePage.rules.table.effectiveFrom")
                        }}</TableHead
                      >
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow v-for="rule in priceRules" :key="rule.id">
                      <TableCell class="text-sm text-gray-900">{{
                        rule.description || "-"
                      }}</TableCell>
                      <TableCell class="text-center">
                        <Badge variant="secondary" class="font-mono text-xs">
                          {{
                            rule.is_enabled ? t("common.yes") : t("common.no")
                          }}
                        </Badge>
                      </TableCell>
                      <TableCell class="text-sm">{{
                        rule.usage_type
                      }}</TableCell>
                      <TableCell class="text-sm">{{
                        rule.media_type || "-"
                      }}</TableCell>
                      <TableCell
                        class="text-right text-sm font-mono text-gray-600"
                      >
                        {{ rule.price_in_micro_units / 1000 }}
                        {{ selectedPlan?.currency }}
                      </TableCell>
                      <TableCell class="text-xs text-gray-500">
                        {{ formatTimestamp(rule.effective_from) }}
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <!-- Custom Fields Section -->
      <Card>
        <CardHeader>
          <CardTitle>{{ t("modelEditPage.sectionCustomFields") }}</CardTitle>
        </CardHeader>
        <CardContent class="space-y-4">
          <div
            v-if="
              editingData.custom_fields && editingData.custom_fields.length > 0
            "
            class="space-y-3"
          >
            <div class="space-y-3 md:hidden">
              <MobileCrudCard
                v-for="field in editingData.custom_fields"
                :key="field.id"
                :title="field.field_name"
                :description="field.description || '-'"
              >
                <div class="grid grid-cols-1 gap-3">
                  <div class="space-y-1">
                    <p class="text-[11px] font-medium uppercase tracking-wide text-gray-500">
                      {{ t("modelEditPage.tableHeaderFieldValue") }}
                    </p>
                    <p class="break-all font-mono text-sm text-gray-700">
                      {{ field.field_value }}
                    </p>
                  </div>
                  <div class="space-y-1">
                    <p class="text-[11px] font-medium uppercase tracking-wide text-gray-500">
                      {{ t("modelEditPage.tableHeaderFieldType") }}
                    </p>
                    <div>
                      <Badge variant="secondary" class="font-mono text-xs">
                        {{ field.field_type }}
                      </Badge>
                    </div>
                  </div>
                </div>

                <template #actions>
                  <Button
                    variant="ghost"
                    size="sm"
                    class="w-full text-red-600 hover:bg-red-50 hover:text-red-700"
                    @click="handleUnlinkCustomField(field.id!)"
                  >
                    <Trash2 class="mr-1.5 h-4 w-4" />
                    {{ t("common.delete") }}
                  </Button>
                </template>
              </MobileCrudCard>
            </div>

            <div class="hidden overflow-hidden rounded-lg border border-gray-200 md:block">
              <Table>
                <TableHeader>
                  <TableRow class="bg-gray-50/80 hover:bg-gray-50/80">
                    <TableHead
                      class="text-xs font-medium text-gray-500 uppercase tracking-wider"
                      >{{ t("modelEditPage.tableHeaderFieldName") }}</TableHead
                    >
                    <TableHead
                      class="text-xs font-medium text-gray-500 uppercase tracking-wider"
                      >{{ t("modelEditPage.tableHeaderFieldValue") }}</TableHead
                    >
                    <TableHead
                      class="text-xs font-medium text-gray-500 uppercase tracking-wider"
                      >{{ t("modelEditPage.tableHeaderDescription") }}</TableHead
                    >
                    <TableHead
                      class="text-xs font-medium text-gray-500 uppercase tracking-wider"
                      >{{ t("modelEditPage.tableHeaderFieldType") }}</TableHead
                    >
                    <TableHead class="w-[80px] text-right"></TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow
                    v-for="field in editingData.custom_fields"
                    :key="field.id"
                  >
                    <TableCell class="text-sm font-medium text-gray-900">{{
                      field.field_name
                    }}</TableCell>
                    <TableCell
                      class="break-all text-sm font-mono text-gray-600"
                      >{{ field.field_value }}</TableCell
                    >
                    <TableCell class="text-sm text-gray-500">{{
                      field.description || "-"
                    }}</TableCell>
                    <TableCell>
                      <Badge variant="secondary" class="font-mono text-xs">{{
                        field.field_type
                      }}</Badge>
                    </TableCell>
                    <TableCell class="text-right">
                      <Button
                        variant="ghost"
                        size="sm"
                        class="text-gray-400 hover:text-red-600"
                        @click="handleUnlinkCustomField(field.id!)"
                      >
                        <Trash2 class="h-3.5 w-3.5" />
                      </Button>
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </div>
          </div>

          <div class="flex flex-col gap-3 border-t border-gray-100 pt-4 sm:flex-row sm:items-center">
            <div class="w-full sm:max-w-sm">
              <Select v-model="selectedCustomFieldId">
                <SelectTrigger class="w-full">
                  <SelectValue
                    :placeholder="
                      t('modelEditPage.placeholderSelectCustomField')
                    "
                  />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem
                    v-for="field in availableCustomFields"
                    :key="field.id"
                    :value="field.id!.toString()"
                  >
                    {{ field.displayName }}
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button
              variant="default"
              class="w-full sm:w-auto"
              @click="handleLinkCustomField"
              :disabled="!selectedCustomFieldId"
            >
              {{ t("modelEditPage.buttonAddCustomField") }}
            </Button>
          </div>
        </CardContent>
      </Card>

        <div class="flex flex-col gap-2 border-t border-gray-100 pt-4 mt-2 sm:flex-row sm:justify-end">
          <Button
            variant="ghost"
            class="w-full text-gray-600 sm:w-auto"
            @click="handleNavigateBack"
            >{{ t("common.cancel") }}</Button
          >
          <Button variant="default" class="w-full sm:w-auto" @click="handleSaveModel">{{
            t("common.save")
          }}</Button>
        </div>
      </div>
    </div>
  </div>
</template>
