// front/src/pages/AccessControl.vue
<template>
  <div class="p-6 space-y-6">
    <div class="flex justify-between items-start">
      <div>
        <h1 class="text-lg font-semibold text-gray-900 tracking-tight">
          {{ $t("accessControlPage.title") }}
        </h1>
        <p class="mt-1 text-sm text-gray-500">
          {{ $t("accessControlPage.description") }}
        </p>
      </div>
      <Button
        @click="handleOpenAddModal"
        variant="outline"
        :disabled="providersLoading || storeLoading"
      >
        <Plus class="h-4 w-4 mr-1.5" />
        {{ $t("accessControlPage.addPolicy") }}
      </Button>
    </div>

    <!-- Data Table -->
    <div v-if="storeLoading" class="flex items-center justify-center py-16">
      <Loader2 class="h-5 w-5 animate-spin mr-2" />
      <span class="text-sm text-gray-500">{{
        $t("accessControlPage.loading")
      }}</span>
    </div>
    <div
      v-else-if="!store.policies.length"
      class="flex flex-col items-center justify-center py-20"
    >
      <ShieldAlert class="h-10 w-10 stroke-1 text-gray-400 mb-2" />
      <span class="text-sm font-medium text-gray-500">{{
        $t("accessControlPage.noData")
      }}</span>
    </div>
    <div v-else class="border border-gray-200 rounded-lg overflow-hidden">
      <Table>
        <TableHeader>
          <TableRow class="bg-gray-50/80 hover:bg-gray-50/80">
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("accessControlPage.table.name") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("accessControlPage.table.defaultAction") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("accessControlPage.table.description") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider"
              >{{ $t("accessControlPage.table.rules") }}</TableHead
            >
            <TableHead
              class="text-xs font-medium text-gray-500 uppercase tracking-wider text-right"
              >{{ $t("accessControlPage.table.actions") }}</TableHead
            >
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow v-for="policy in store.policies" :key="policy.id">
            <TableCell class="text-sm font-medium text-gray-900">{{
              policy.name
            }}</TableCell>
            <TableCell>
              <Badge variant="secondary" class="font-mono text-xs">{{
                $t(`accessControlPage.modal.option${policy.default_action}`)
              }}</Badge>
            </TableCell>
            <TableCell class="text-sm text-gray-600">{{
              policy.description || "/"
            }}</TableCell>
            <TableCell class="text-sm text-gray-600">{{
              $t("accessControlPage.table.rulesCount", {
                count: policy.rules?.length || 0,
              })
            }}</TableCell>
            <TableCell class="text-right">
              <Button
                variant="ghost"
                size="sm"
                @click="handleOpenEditModal(policy.id)"
                :disabled="providersLoading || storeLoading"
              >
                <Edit2 class="h-3.5 w-3.5 mr-1" />
                {{ $t("common.edit") }}
              </Button>
              <Button
                variant="ghost"
                size="sm"
                class="text-gray-400 hover:text-red-600"
                @click="handleDeletePolicy(policy.id, policy.name)"
              >
                <Trash2 class="h-3.5 w-3.5 mr-1" />
                {{ $t("common.delete") }}
              </Button>
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </div>

    <!-- Edit/Add Modal -->
    <Dialog :open="showEditModal" @update:open="setShowEditModal">
      <DialogContent
        class="max-w-4xl max-h-[90vh] flex flex-col p-6 overflow-hidden"
      >
        <DialogHeader>
          <DialogTitle class="text-lg font-semibold text-gray-900">{{
            editingPolicy.id
              ? $t("accessControlPage.modal.titleEdit")
              : $t("accessControlPage.modal.titleAdd")
          }}</DialogTitle>
        </DialogHeader>

        <div class="space-y-4 overflow-y-auto flex-1 pr-2">
          <!-- Policy Fields -->
          <div class="space-y-4">
            <div>
              <Label class="text-gray-700"
                >{{ $t("accessControlPage.modal.labelName")
                }}<span class="text-red-500 ml-0.5">*</span></Label
              >
              <Input class="mt-1.5" v-model="editingPolicy.name" />
            </div>

            <div class="grid grid-cols-2 gap-4">
              <div>
                <Label class="text-gray-700">{{
                  $t("accessControlPage.modal.labelDefaultAction")
                }}</Label>
                <Select v-model="editingPolicy.default_action">
                  <SelectTrigger class="w-full mt-1.5">
                    <SelectValue
                      :placeholder="
                        $t('accessControlPage.modal.placeholderDefaultAction')
                      "
                    />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem
                      v-for="opt in defaultActionOptions"
                      :key="opt.value"
                      :value="opt.value"
                    >
                      {{ opt.label }}
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label class="text-gray-700">{{
                  $t("accessControlPage.modal.labelDescription")
                }}</Label>
                <Input class="mt-1.5" v-model="editingPolicy.description" />
              </div>
            </div>
          </div>

          <hr class="my-6 border-gray-100" />

          <!-- Rules Section -->
          <div class="space-y-4">
            <div class="flex justify-between items-center">
              <h4 class="text-sm font-medium text-gray-900">
                {{ $t("accessControlPage.rules.title") }}
              </h4>
              <Button @click="addRule" variant="outline" size="sm">
                <Plus class="h-3.5 w-3.5 mr-1" />
                {{ $t("accessControlPage.rules.addRule") }}
              </Button>
            </div>

            <div
              class="max-h-80 overflow-y-auto border border-gray-200 rounded-lg p-2 space-y-2 bg-gray-50"
            >
              <div
                v-if="!editingPolicy.rules.length"
                class="flex flex-col items-center justify-center py-10"
              >
                <span class="text-sm font-medium text-gray-500">{{
                  $t("accessControlPage.rules.noRules")
                }}</span>
              </div>

              <div
                v-for="(rule, index) in editingPolicy.rules"
                :key="index"
                class="p-5 bg-white border border-gray-200 rounded-lg"
              >
                <div
                  class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 items-end"
                >
                  <!-- Rule Type -->
                  <div>
                    <Label class="text-gray-700 block mb-1.5">{{
                      $t("accessControlPage.rules.labelRuleType")
                    }}</Label>
                    <Select v-model="rule.rule_type">
                      <SelectTrigger
                        class="w-full focus:ring-1 focus:ring-gray-300"
                      >
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem
                          v-for="opt in ruleTypeOptions"
                          :key="opt.value"
                          :value="opt.value"
                        >
                          {{ opt.label }}
                        </SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <!-- Scope -->
                  <div>
                    <Label class="text-gray-700 block mb-1.5">{{
                      $t("accessControlPage.rules.labelScope")
                    }}</Label>
                    <Select
                      v-model="rule.scope"
                      @update:model-value="onScopeChange(rule)"
                    >
                      <SelectTrigger
                        class="w-full focus:ring-1 focus:ring-gray-300"
                      >
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem
                          v-for="opt in scopeOptions"
                          :key="opt.value"
                          :value="opt.value"
                        >
                          {{ opt.label }}
                        </SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <!-- Provider -->
                  <div class="md:col-span-2 lg:col-span-2">
                    <Label class="text-gray-700 block mb-1.5 truncate">{{
                      $t("accessControlPage.rules.labelProvider")
                    }}</Label>
                    <Select
                      v-model="rule.provider_id"
                      @update:model-value="onProviderChange(rule)"
                    >
                      <SelectTrigger
                        class="w-full focus:ring-1 focus:ring-gray-300"
                      >
                        <SelectValue
                          :placeholder="
                            $t('accessControlPage.rules.placeholderProvider')
                          "
                          class="truncate"
                        />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem
                          v-for="opt in providerOptions"
                          :key="opt.value"
                          :value="String(opt.value)"
                        >
                          {{ opt.label }}
                        </SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <!-- Model -->
                  <div
                    v-if="rule.scope === 'MODEL'"
                    class="md:col-span-2 lg:col-span-2"
                  >
                    <Label class="text-gray-700 block mb-1.5 truncate">{{
                      $t("accessControlPage.rules.labelModel")
                    }}</Label>
                    <Select
                      v-model="rule.model_id"
                      :disabled="!rule.provider_id"
                    >
                      <SelectTrigger
                        class="w-full focus:ring-1 focus:ring-gray-300"
                      >
                        <SelectValue
                          :placeholder="
                            $t('accessControlPage.rules.placeholderModel')
                          "
                          class="truncate"
                        />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem
                          v-for="opt in getModelOptions(rule.provider_id)"
                          :key="opt.value"
                          :value="String(opt.value)"
                        >
                          {{ opt.label }}
                        </SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <!-- Priority -->
                  <div>
                    <Label class="text-gray-700 block mb-1.5 truncate">{{
                      $t("accessControlPage.rules.labelPriority")
                    }}</Label>
                    <Input
                      class="w-full focus:ring-1 focus:ring-gray-300"
                      type="number"
                      v-model.number="rule.priority"
                    />
                  </div>

                  <!-- Actions -->
                  <div>
                    <Button
                      type="button"
                      @click="removeRule(index)"
                      variant="outline"
                      class="w-full text-red-600 border-red-200 hover:bg-red-50 hover:text-red-700 transition-colors"
                    >
                      <Trash2 class="h-4 w-4 mr-2" />
                      {{ $t("accessControlPage.rules.deleteRule") }}
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <DialogFooter class="border-t border-gray-100 pt-4 mt-2">
          <Button
            @click="handleCloseModal"
            variant="ghost"
            class="text-gray-600"
            >{{ $t("common.cancel") }}</Button
          >
          <Button @click="handleSavePolicy" variant="default">{{
            $t("common.save")
          }}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import { useI18n } from "vue-i18n";
import { Api } from "@/services/request";
import { useAccessControlStore } from "@/store/accessControlStore";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { Plus, Edit2, Trash2, ShieldAlert, Loader2 } from "lucide-vue-next";

const { t: $t } = useI18n();
const store = useAccessControlStore();

// UI States
const storeLoading = ref(true);
const providersLoading = ref(true);
const showEditModal = ref(false);

const setShowEditModal = (val: boolean) => {
  showEditModal.value = val;
};

// Data Models
interface Model {
  id: number;
  model_name: string;
}
interface Provider {
  id: number;
  name: string;
}
interface ProviderDetail {
  provider: Provider;
  models: Model[];
}

const providers = ref<ProviderDetail[]>([]);

const newPolicyTemplate = () => ({
  id: null as number | null,
  name: "",
  default_action: "ALLOW" as "ALLOW" | "DENY",
  description: "",
  rules: [] as any[],
});

const newRuleTemplate = () => ({
  id: null,
  rule_type: "ALLOW",
  priority: 0,
  scope: "PROVIDER",
  provider_id: null as string | null,
  model_id: null as string | null,
  description: "",
  is_enabled: true,
});

const editingPolicy = ref(newPolicyTemplate());

// Options
const defaultActionOptions = computed(() =>
  ["ALLOW", "DENY"].map((o) => ({
    value: o,
    label: $t(`accessControlPage.modal.option${o}`),
  })),
);
const ruleTypeOptions = computed(() =>
  ["ALLOW", "DENY"].map((o) => ({
    value: o,
    label: $t(`accessControlPage.modal.option${o}`),
  })),
);
const scopeOptions = computed(() =>
  ["PROVIDER", "MODEL"].map((o) => ({
    value: o,
    label: $t(`accessControlPage.rules.scope${o}`),
  })),
);
const providerOptions = computed(() =>
  providers.value.map((p) => ({
    value: p.provider.id,
    label: p.provider.name,
  })),
);

const getModelOptions = (providerIdStr: string | null) => {
  const providerId = Number(providerIdStr);
  if (!providerId || isNaN(providerId)) return [];
  const pDetail = providers.value.find((p) => p.provider.id === providerId);
  return (pDetail?.models || []).map((m) => ({
    value: m.id,
    label: m.model_name,
  }));
};

const onScopeChange = (rule: any) => {
  if (rule.scope === "PROVIDER") rule.model_id = null;
};

const onProviderChange = (rule: any) => {
  rule.model_id = null;
};

// Methods
const fetchProvidersWithModelsAPI = async () => {
  try {
    const response = await Api.getProviderDetailList();
    return response as unknown as ProviderDetail[];
  } catch (error) {
    console.error("Failed to fetch providers:", error);
    return [];
  }
};

const fetchPolicyDetailAPI = async (id: number) => {
  try {
    const response = await Api.getAccessControlDetail(id);
    return response as any;
  } catch (error) {
    console.error("Failed to fetch policy detail:", error);
    return null;
  }
};

const handleOpenAddModal = () => {
  editingPolicy.value = newPolicyTemplate();
  showEditModal.value = true;
};

const handleOpenEditModal = async (id: number) => {
  const detail = await fetchPolicyDetailAPI(id);
  if (detail) {
    editingPolicy.value = {
      id: detail.id,
      name: detail.name,
      default_action: detail.default_action.toUpperCase(),
      description: detail.description,
      rules: (detail.rules || [])
        .map((r: any) => ({
          id: r.id,
          rule_type: r.rule_type.toUpperCase(),
          priority: r.priority,
          scope: r.scope.toUpperCase(),
          provider_id: r.provider_id ? String(r.provider_id) : null,
          model_id: r.model_id ? String(r.model_id) : null,
          description: r.description,
          is_enabled: r.is_enabled,
        }))
        .sort((a: any, b: any) => a.priority - b.priority),
    };
    showEditModal.value = true;
  } else {
    alert($t("accessControlPage.alert.loadDetailFailed"));
  }
};

const handleCloseModal = () => {
  showEditModal.value = false;
};

const handleDeletePolicy = async (id: number, name: string) => {
  if (confirm($t("accessControlPage.confirmDelete", { name }))) {
    try {
      await Api.deleteAccessControl(id);
      await store.fetchPolicies();
    } catch (error: any) {
      alert(
        $t("accessControlPage.alert.deleteFailed", {
          error: error.message || "Unknown Error",
        }),
      );
    }
  }
};

const handleSavePolicy = async () => {
  if (!editingPolicy.value.name) {
    alert($t("accessControlPage.alert.nameRequired"));
    return;
  }

  const payload = {
    name: editingPolicy.value.name,
    default_action: editingPolicy.value.default_action,
    description: editingPolicy.value.description || null,
    rules: editingPolicy.value.rules.map((rule) => ({
      rule_type: rule.rule_type,
      priority: Number(rule.priority) || 0,
      scope: rule.scope,
      provider_id: rule.provider_id ? Number(rule.provider_id) : null,
      model_id:
        rule.scope === "MODEL" && rule.model_id ? Number(rule.model_id) : null,
      description: rule.description || null,
      is_enabled: rule.is_enabled,
    })),
  };

  try {
    if (editingPolicy.value.id) {
      await Api.updateAccessControl(editingPolicy.value.id, payload);
    } else {
      await Api.createAccessControl(payload);
    }
    showEditModal.value = false;
    await store.fetchPolicies();
  } catch (error: any) {
    alert(
      $t("accessControlPage.alert.saveFailed", {
        error: error.message || "Unknown Error",
      }),
    );
  }
};

const addRule = () => {
  editingPolicy.value.rules.push(newRuleTemplate());
};

const removeRule = (index: number) => {
  editingPolicy.value.rules.splice(index, 1);
};

onMounted(async () => {
  storeLoading.value = true;
  await store.fetchPolicies();
  storeLoading.value = false;

  providersLoading.value = true;
  providers.value = await fetchProvidersWithModelsAPI();
  providersLoading.value = false;
});
</script>

// front/src/routes/_layout/access_control.tsx
import { createSignal, For, Show, Accessor, Setter, onMount, createMemo } from 'solid-js';
import { createFileRoute, useRouter } from '@tanstack/solid-router';
import { Button } from '@/components/ui/Button';
import {
    DialogRoot,
    DialogContent,
    DialogHeader,
    DialogFooter,
    DialogTitle,
} from '@/components/ui/Dialog';
import { Select } from '@/components/ui/Select';
import { TextField, NumberField } from '@/components/ui/Input';
import {
    TableRoot,
    TableHeader,
    TableBody,
    TableRow,
    TableColumnHeader,
    TableCell,
} from '@/components/ui/Table';
import { request } from '@/services/api';
import { useI18n } from '@/i18n';
import { policies as globalPolicies, loadPolicies, type AccessControlPolicyFromAPI } from '@/store/accessControlStore';

// --- Type Definitions ---

interface Model {
    id: number;
    model_name: string;
}

interface Provider {
    id: number;
    name: string;
}

interface ProviderDetail {
    provider: Provider;
    models: Model[];
}

// UI representation of an AccessControlRule
interface AccessControlRuleUI {
    id: number | null; // null for new rules
    rule_type: 'ALLOW' | 'DENY';
    priority: number;
    scope: 'PROVIDER' | 'MODEL';
    provider_id: number | null;
    model_id: number | null;
    description: string | null;
    is_enabled: boolean;
}

// Represents a full policy in the UI for editing
interface AccessControlPolicyUI {
    id: number | null; // null for new policy
    name: string;
    default_action: 'ALLOW' | 'DENY';
    description: string | null;
    rules: AccessControlRuleUI[];
}

const newPolicyTemplate = (): AccessControlPolicyUI => ({
    id: null,
    name: '',
    default_action: 'ALLOW',
    description: '',
    rules: []
});

const newRuleTemplate = (): AccessControlRuleUI => ({
    id: null,
    rule_type: 'ALLOW',
    priority: 0,
    scope: 'PROVIDER',
    provider_id: null,
    model_id: null,
    description: '',
    is_enabled: true,
});

// --- API Functions ---

const fetchProvidersWithModelsAPI = async (): Promise<ProviderDetail[]> => {
    try {
        const response = await request("/ai/manager/api/provider/detail/list");
        return response || [];
    } catch (error) {
        console.error("Failed to fetch providers with models:", error);
        return [];
    }
};

export const Route = createFileRoute('/_layout/access_control')({
    component: AccessControlPage,
});

const fetchPolicyDetailAPI = async (id: number): Promise<AccessControlPolicyFromAPI | null> => {
    try {
        const response = await request(`/ai/manager/api/access_control/${id}`);
        return response || null;
    } catch (error) {
        console.error("Failed to fetch policy detail:", error);
        return null;
    }
};

const savePolicyAPI = async (policy: AccessControlPolicyUI): Promise<any> => {
    const payload = {
        name: policy.name,
        default_action: policy.default_action,
        description: policy.description || null,
        rules: policy.rules.map(rule => ({
            rule_type: rule.rule_type,
            priority: Number(rule.priority) || 0,
            scope: rule.scope,
            provider_id: rule.provider_id,
            model_id: rule.scope === 'MODEL' ? rule.model_id : null,
            description: rule.description || null,
            is_enabled: rule.is_enabled,
        })),
    };

    const url = policy.id ? `/ai/manager/api/access_control/${policy.id}` : '/ai/manager/api/access_control';
    const method = policy.id ? 'PUT' : 'POST';

    return request(url, {
        method: method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
    });
};

const deletePolicyAPI = async (id: number): Promise<any> => {
    return request(`/ai/manager/api/access_control/${id}`, { method: 'DELETE' });
};


// --- Helper to transform API detail to UI state ---
function transformApiDetailToUiState(apiDetail: AccessControlPolicyFromAPI): AccessControlPolicyUI {
    return {
        id: apiDetail.id,
        name: apiDetail.name,
        default_action: (apiDetail.default_action as string).toUpperCase() as 'ALLOW' | 'DENY',
        description: apiDetail.description,
        rules: (apiDetail.rules || []).map(rule => ({
            id: rule.id,
            rule_type: rule.rule_type.toUpperCase() as 'ALLOW' | 'DENY',
            priority: rule.priority,
            scope: rule.scope.toUpperCase() as 'PROVIDER' | 'MODEL',
            provider_id: rule.provider_id,
            model_id: rule.model_id,
            description: rule.description,
            is_enabled: rule.is_enabled,
        })).sort((a, b) => a.priority - b.priority), // Sort by priority for consistent display
    };
}


export default function AccessControlPage() {
    const [t] = useI18n();
    const router = useRouter();
    const [providers, setProviders] = createSignal<ProviderDetail[]>([]);
    const [providersLoading, setProvidersLoading] = createSignal(true);

    onMount(async () => {
        loadPolicies(); // This has its own loading state in the store
        const providersData = await fetchProvidersWithModelsAPI();
        setProviders(providersData || []);
        setProvidersLoading(false);
    });

    const ruleTypeOptions = createMemo(() => ['ALLOW', 'DENY'].map(o => ({ value: o, label: t(`accessControlPage.modal.option${o}`) })));
    const scopeOptions = createMemo(() => ['PROVIDER', 'MODEL'].map(o => ({ value: o, label: t(`accessControlPage.rules.scope${o}`) })));

    const policies = globalPolicies;

    const [showEditModal, setShowEditModal] = createSignal(false);
    const [editingPolicy, setEditingPolicy] = createSignal<AccessControlPolicyUI>(newPolicyTemplate());

    const defaultActionOptions = createMemo(() => ['ALLOW', 'DENY'].map(o => ({ value: o, label: t(`accessControlPage.modal.option${o}`) })));
    const selectedDefaultAction = createMemo(() => defaultActionOptions().find(o => o.value === (editingPolicy()?.default_action || 'ALLOW')));

    const providerOptions = createMemo(() => (providers() || []).map(p => ({ value: p.provider.id, label: p.provider.name })));

    const handleOpenAddModal = () => {
        setEditingPolicy(newPolicyTemplate());
        setShowEditModal(true);
    };

    const handleOpenEditModal = async (id: number) => {
        const detail = await fetchPolicyDetailAPI(id);
        if (detail) {
            setEditingPolicy(transformApiDetailToUiState(detail));
            setShowEditModal(true);
        } else {
            alert(t('accessControlPage.alert.loadDetailFailed'));
        }
    };

    const handleCloseModal = () => {
        setShowEditModal(false);
    };

    const handleSavePolicy = async () => {
        const policy = editingPolicy();
        if (!policy) return;
        if (!policy.name) {
            alert(t('accessControlPage.alert.nameRequired'));
            return;
        }

        try {
            await savePolicyAPI(policy);
            setShowEditModal(false);
            router.invalidate();
        } catch (error) {
            console.error("Failed to save policy:", error);
            alert(t('accessControlPage.alert.saveFailed', { error: error instanceof Error ? error.message : t('unknownError') }));
        }
    };

    const handleDeletePolicy = async (id: number, name: string) => {
        if (confirm(t('accessControlPage.confirmDelete', { name }))) {
            try {
                await deletePolicyAPI(id);
                router.invalidate();
            } catch (error) {
                console.error("Failed to delete policy:", error);
                alert(t('accessControlPage.alert.deleteFailed', { error: error instanceof Error ? error.message : t('unknownError') }));
            }
        }
    };

    // --- Rule Management ---
    const addRule = () => {
        const currentPolicy = editingPolicy();
        if (!currentPolicy) return;
        setEditingPolicy({
            ...currentPolicy,
            rules: [...currentPolicy.rules, newRuleTemplate()]
        });
    };

    const removeRule = (index: number) => {
        const currentPolicy = editingPolicy();
        if (!currentPolicy) return;
        const updatedRules = [...currentPolicy.rules];
        updatedRules.splice(index, 1);
        setEditingPolicy({
            ...currentPolicy,
            rules: updatedRules
        });
    };

    const updateRuleField = <T extends keyof AccessControlRuleUI>(index: number, field: T, value: AccessControlRuleUI[T]) => {
        const currentPolicy = editingPolicy();
        if (!currentPolicy) return;

        const updatedRules = currentPolicy.rules.map((rule, i) =>
            i === index ? { ...rule, [field]: value } : rule
        );

        // Reset dependent fields on scope change
        if (field === 'scope') {
            const updatedRule = updatedRules[index];
            if (value === 'PROVIDER') {
                updatedRule.model_id = null;
            }
        } else if (field === 'provider_id') {
            const updatedRule = updatedRules[index];
            updatedRule.model_id = null; // Reset model if provider changes
        }

        setEditingPolicy({ ...currentPolicy, rules: updatedRules });
    };


    // --- Helper functions for display ---
    const getProviderName = (providerId: number | null): string => {
        if (providerId === null) return '所有 Provider';
        const pDetail = providers()?.find(p => p.provider.id === providerId);
        return pDetail ? pDetail.provider.name : '未知 Provider';
    };

    const getModelName = (providerId: number | null, modelId: number | null): string => {
        if (modelId === null) return 'N/A';
        if (providerId === null) return '未知 Model (无 Provider)';
        const pDetail = providers()?.find(p => p.provider.id === providerId);
        if (!pDetail || !pDetail.models) return '未知 Model (Provider 无模型)';
        const model = pDetail.models.find(m => m.id === modelId);
        return model ? model.model_name : '未知 Model';
    };

    const getModelsForProvider = (providerId: number | null): Model[] => {
        if (providerId === null || !providers()) return [];
        const pDetail = providers()?.find(p => p.provider.id === providerId);
        return (pDetail?.models || []).map(mDetail => mDetail.model);
    };


    const getModelById = (providerId: number | null, modelId: number | null): Model | null => {
        if (modelId === null || providerId === null) return null;
        const models = getModelsForProvider(providerId);
        const model = models.find(m => m.id === modelId);
        return model || null;
    };


    return (
        <div class="p-4 space-y-6">
            <div class="flex justify-between items-center mb-4">
                <h1 class="text-2xl font-semibold text-gray-800">{t('accessControlPage.title')}</h1>
                <Button onClick={handleOpenAddModal} variant="primary" disabled={providersLoading() || policies.loading}>{t('accessControlPage.addPolicy')}</Button>
            </div>

            {/* Data Table */}
            <Show when={policies.loading}>
                <div class="text-center py-4 text-gray-500">{t('accessControlPage.loading')}</div>
            </Show>
            <Show when={!policies.loading && policies.error}>
                <div class="text-center py-4 text-red-500">{t('accessControlPage.error')}</div>
            </Show>
            <Show when={!policies.loading && !policies.error && policies()?.length === 0}>
                <div class="text-center py-4 text-gray-500">{t('accessControlPage.noData')}</div>
            </Show>
            <Show when={!policies.loading && !policies.error && policies() && policies()!.length > 0}>
                <div class="overflow-x-auto shadow-md rounded-lg border border-gray-200">
                    <TableRoot>
                        <TableHeader>
                            <TableRow>
                                <TableColumnHeader>{t('accessControlPage.table.name')}</TableColumnHeader>
                                <TableColumnHeader>{t('accessControlPage.table.defaultAction')}</TableColumnHeader>
                                <TableColumnHeader>{t('accessControlPage.table.description')}</TableColumnHeader>
                                <TableColumnHeader>{t('accessControlPage.table.rules')}</TableColumnHeader>
                                <TableColumnHeader>{t('accessControlPage.table.actions')}</TableColumnHeader>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            <For each={policies()}>{(policy) =>
                                <TableRow>
                                    <TableCell>{policy.name}</TableCell>
                                    <TableCell>{t(`accessControlPage.modal.option${policy.default_action}`)}</TableCell>
                                    <TableCell>{policy.description || '/'}</TableCell>
                                    <TableCell>{t('accessControlPage.table.rulesCount', { count: policy.rules?.length || 0 })}</TableCell>
                                    <TableCell class="space-x-2">
                                        <Button type="text" onClick={() => handleOpenEditModal(policy.id)} variant="primary" size="sm" disabled={providersLoading() || policies.loading}>{t('common.edit')}</Button>
                                        <Button type="text" onClick={() => handleDeletePolicy(policy.id, policy.name)} variant="destructive" size="sm">{t('common.delete')}</Button>
                                    </TableCell>
                                </TableRow>
                            }</For>
                        </TableBody>
                    </TableRoot>
                </div>
            </Show>

            {/* Edit/Add Modal */}
            <DialogRoot open={showEditModal()} onOpenChange={setShowEditModal}>
                <DialogContent class="max-w-4xl max-h-[90vh] flex flex-col">
                    <DialogHeader>
                        <DialogTitle>{editingPolicy()?.id ? t('accessControlPage.modal.titleEdit') : t('accessControlPage.modal.titleAdd')}</DialogTitle>
                    </DialogHeader>
                    <div class="space-y-4 overflow-y-auto">
                        {/* Policy Fields */}
                        <TextField
                            label={t('accessControlPage.modal.labelName')}
                            value={editingPolicy()?.name || ''}
                            onChange={(v) => setEditingPolicy(p => ({ ...p!, name: v }))}
                        />
                        <Select
                            label={t('accessControlPage.modal.labelDefaultAction')}
                            value={selectedDefaultAction()}
                            optionValue="value"
                            optionTextValue="label"
                            onChange={(v) => setEditingPolicy(p => ({ ...p!, default_action: v.value as 'ALLOW' | 'DENY' }))}
                            options={defaultActionOptions()}
                            placeholder={t('accessControlPage.modal.placeholderDefaultAction')}
                        />
                        <TextField
                            label={t('accessControlPage.modal.labelDescription')}
                            value={editingPolicy()?.description || ''}
                            onChange={(v) => setEditingPolicy(p => ({ ...p!, description: v }))}
                            textarea
                            rows={2}
                        />

                        <hr class="my-6" />

                        {/* Rules Section */}
                        <div class="space-y-3">
                            <div class="flex justify-between items-center">
                                <h4 class="text-lg font-medium">{t('accessControlPage.rules.title')}</h4>
                                <Button onClick={addRule} variant="secondary" size="sm">{t('accessControlPage.rules.addRule')}</Button>
                            </div>
                            <div class="max-h-80 overflow-y-auto border rounded p-2 space-y-2">
                                <Show when={editingPolicy()?.rules.length === 0}>
                                    <p class="text-sm text-gray-500 text-center py-2">{t('accessControlPage.rules.noRules')}</p>
                                </Show>
                                <For each={editingPolicy()?.rules}>{(rule, index) => {
                                    const modelOptions = createMemo(() => getModelsForProvider(rule.provider_id).map(m => ({ value: m.id, label: m.model_name })));
                                    const selectedModel = createMemo(() => modelOptions().find(m => m.value === rule.model_id));

                                    return (<div class="p-3 border rounded bg-gray-50 space-y-2">
                                        <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-2 items-end">
                                            {/* Rule Type */}
                                            <div>
                                                <Select
                                                    value={ruleTypeOptions().find(o => o.value === rule.rule_type)}
                                                    onChange={(v) => updateRuleField(index(), 'rule_type', v.value)}
                                                    optionValue="value"
                                                    optionTextValue="label"
                                                    options={ruleTypeOptions()}
                                                    label={t('accessControlPage.rules.labelRuleType')}
                                                />
                                            </div>
                                            {/* Scope */}
                                            <div>
                                                <Select
                                                    value={scopeOptions().find(o => o.value === rule.scope)}
                                                    onChange={(v) => updateRuleField(index(), 'scope', v.value)}
                                                    optionValue="value"
                                                    optionTextValue="label"
                                                    options={scopeOptions()}
                                                    label={t('accessControlPage.rules.labelScope')}
                                                />
                                            </div>
                                            {/* Provider */}
                                            <div classList={{ "lg:col-span-2": rule.scope === 'PROVIDER' }}>
                                                <Select
                                                    value={providerOptions().find(p => p.value === rule.provider_id)}
                                                    optionValue="value"
                                                    optionTextValue="label"
                                                    onChange={(v) => updateRuleField(index(), 'provider_id', v ? v.value : null)}
                                                    options={providerOptions()}
                                                    placeholder={t('accessControlPage.rules.placeholderProvider')}
                                                    label={t('accessControlPage.rules.labelProvider')}
                                                />
                                            </div>
                                            {/* Model */}
                                            <Show when={rule.scope === 'MODEL'}>
                                                <div>
                                                    <Select
                                                        value={selectedModel()}
                                                        onChange={(v) => updateRuleField(index(), 'model_id', v ? v.value : null)}
                                                        optionValue="value"
                                                        optionTextValue="label"
                                                        options={modelOptions()}
                                                        placeholder={t('accessControlPage.rules.placeholderModel')}
                                                        disabled={!rule.provider_id}
                                                        label={t('accessControlPage.rules.labelModel')}
                                                    />
                                                </div>
                                            </Show>
                                            {/* Priority */}
                                            <div>
                                                <NumberField
                                                    label={t('accessControlPage.rules.labelPriority')}
                                                    value={rule.priority}
                                                    onChange={v => updateRuleField(index(), 'priority', isNaN(v) ? 0 : v)}
                                                    step={1}
                                                    formatOptions={{ maximumFractionDigits: 0 }}
                                                />
                                            </div>
                                            {/* Actions */}
                                            <div class="self-end">
                                                <Button type="text" onClick={() => removeRule(index())} variant="destructive" size="sm">{t('accessControlPage.rules.deleteRule')}</Button>
                                            </div>
                                        </div>
                                    </div>)
                                }}</For>
                            </div>
                        </div>
                    </div>
                    <DialogFooter class="pt-6">
                        <Button onClick={handleCloseModal} variant="secondary">{t('common.cancel')}</Button>
                        <Button onClick={handleSavePolicy} variant="primary">{t('common.save')}</Button>
                    </DialogFooter>
                </DialogContent>
            </DialogRoot>
        </div>
    );
}
